networks:
  jpmsb-std:
    external: false
    name: jpmsb-std

services:
  servidor:
    build:
      context: servidor
      dockerfile: Dockerfile
    image: jpmsb/servidor
    networks:
      - jpmsb-std
    deploy:
      mode: replicated
      replicas: 5

  cliente:
    build:
      context: cliente
      dockerfile: Dockerfile
    image: jpmsb/cliente
    networks:
      - jpmsb-std
    deploy:
      mode: replicated
      replicas: 20
    environment:
      - PILOTO_AUTOMATICO="${PILOTO_AUTOMATICO}"
