/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.std;

public class Principal {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Principal().getGreeting());
    }
}
